### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#1]
It's sparse! Add some more info on what exactly this is, why it is, etc.

**Comment by Suryasai369** [comment]
Any ideas you have to how you want to go and where you want to go with this project. We will try to implement it.

**Comment by jeffreycharters** [comment]
We need to add a link to the live site to the readme too. 

https://station-team.netlify.app

If someone wants to jump on that, if not I'll hopefully get on it tonight.
