### ISSUE TITLE
Let people know if they've seen the page before

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#15]
This will require some javascript, keep it all in the `script.js` file.

Use [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to add an item to the use's browser storage saying they've visited the site before. When the site loads, check and see if this item exists. Then change the textContent of a div element to say whether we think the user has visited the site before or not (using their current browser).

**Comment by choco-develop** [comment]
can i try out this too?

**Comment by jeffreycharters** [comment]
Yes, go for it! I've assigned this to you for now.

Add a comment in this issue if you run into any problems or even ask in the #javascript discussion on STTN and I'm sure people will be glad to help.

**Comment by choco-develop** [comment]
Thanks i will get it done
