### ISSUE TITLE
Create a list and style it

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#17]
This one has a few steps:
- [x] Create either an ordered `<ol>` or unordered `<ul>` list, and add some items to it. Can be anything, your favourite sports teams, some songs, funny words, whatever!
- [x] Add an `id` attribute to the tag.
- [x] Add some styling into the CSS file to make it look different.

**Comment by lucifer694u** [comment]
hey can i take up this issue

**Comment by jeffreycharters** [comment]
Have fun!
