### ISSUE TITLE
Add a hero image

### ISSUE THREAD

**Issue by sarajw** [jeffreycharters/station#18]
Make us a nice big header image, that can fill the horizontal space and is a bombastic start to our baby website!

Don't worry about the specific perfect code to add it with - whether as an image or CSS background-image, we can figure out those details later :)

**Comment by jeffreycharters** [comment]
Oh man we're going to look pro.

Do you mind adding in the description what a hero image is, just in case someone is unaware? Please/thanks 😉

**Comment by jeffreycharters** [comment]
Whoever is going to do this -- add the image into a new folder called "images". I thought about having it in "static/images" but I feel just having an images folder will be easier for newcomers to understand.

Does that make sense?

**Comment by sarajw** [comment]
Oh that's a good idea!

**Comment by PaulEdworthy** [comment]
I didn't even see this before I posted the Rick Roll.

Next time I try to be a smart ass I'll check the issues first.

**Comment by thatgirldorian** [comment]
Hi folks!

I can handle this one. Just sent it a request. :)
