### ISSUE TITLE
Update "get started" link on page to point to this repo

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#26]
Right now the user will get a 404, but I think the main page of the repo with the "readme" is a good starting point. So we just need to update location.href to the main repo github address. Can we make the link using an `<a>` instead of a button? I didn't look closely enough at the styling to see if that would work. It would be better *semantic HTML* (make a link out of a `<a>` tag instead of a button).

**Comment by thatgirldorian** [comment]
I just fixed this :)

**Comment by jeffreycharters** [comment]
Nice, it's live on the main page now, thanks!
