### ISSUE TITLE
Add some meta tags

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#33]
If I leave this link on our Discord forum, for instance, we don't get that cool preview that some sites have.

Can someone look into how to do this? Pretty sure it involves some sort of HTML `meta` tags, but I don't know which. Feel free to leave a comment below if you want any assistance.

**Comment by jeffreycharters** [comment]
It works!! Nice work @loisteo!

**Comment by jeffreycharters** [comment]
I just tried putting a link to the site on Twitter and it didn't work for some reason!

When I try putting in the site address (https://station-team.netlify.app, presently) on [Twitter's card validator](https://cards-dev.twitter.com/validator) I am getting an error and says it is unable to render.

The good news is that it *did* work in Discord, so great start! We'll need to figure out why it isn't working with Twitter and implement a fix.

**Comment by jeffreycharters** [comment]
I think we might need to change the tags that start with `<meta property="twitter:...` just need to have `property` replaced with name? Might need to investigate a bit more.

**Comment by loisteo** [comment]
Is it still not working? I'm able to see the card rendered if I pasted the link in Twitter.

**Comment by jeffreycharters** [comment]
It does seem to work, not sure what my problem was earlier. So I'll reclose this and if for some reason we have issues we can always come back to it.

Thanks for your contribution, @loisteo!
