### ISSUE TITLE
[Feature] Implement dark/light mode

### ISSUE THREAD

**Issue by abitsalihu** [jeffreycharters/station#36]
I noticed the website does not have a dark/light mode, I would like to implement this using vanilla JS.

**Comment by jeffreycharters** [comment]
Just to add a little context to this issue - apparently browsers will use your system settings to automatically use light mode or dark mode. I did a quick web search and found [an article about this](https://www.howtogeek.com/440920/browsers-are-bringing-automatic-dark-mode-to-websites/) from a few years ago.

But I agree that it would be nice to have a toggle between the two, and vanilla JS is a great way to do it!

**Comment by abitsalihu** [comment]
I'm not sure exactly how it works either, should I start on this issue to do it with vanilla JS or do you want to leave it for someone else?

**Comment by jeffreycharters** [comment]
No, you can go for it! Might need to do a bit of reading/learning but have a try with js.

**Comment by abitsalihu** [comment]
Alright assign me to this one. :)

**Comment by jeffreycharters** [comment]
All yours! Leave a comment here if you get stuck, we're happy to help where we can.

**Comment by jeffreycharters** [comment]
I'll close this for now, we'll see in the future if we want/need to make any changes. A good start!
