### ISSUE TITLE
Add links to beginner resources

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#4]
Not sure if we want these in the readme or on the actual site but would probably be good to give very new beginners some easy-to-understand articles to get an idea of what's happening here and how they can go about getting started.

But I want to try to keep the repo as sparse as possible so newbies don't get overwhelmed by a ton of files.

**Comment by lucifer694u** [comment]
hey i am newbie can you tell me about this issue

**Comment by jeffreycharters** [comment]
Hi @lucifer694u! Since we expect a lot of people coming here to have very little knowledge of using Github, it would be nice to provide links to guides/tutorials that will be helpful but not overwhelming.

I am learning at the same time so don't know of any good ones right now. If you know of some, you are welcome to try cloning/forking this repository and adding them to the `index.html` file. You might even find some good ones by going through the forking and Pull Request process!

Does that help?

**Comment by lucifer694u** [comment]
yes it helps @jeffreycharters I will work on this

**Comment by jeffreycharters** [comment]
I look forward to it, let me know if you need anything along the way 😊

**Comment by jeffreycharters** [comment]
@sarajw dropped this link on the discord, might be helpful for somebody:

https://www.koskila.net/how-to-git-merge-upstream/
