### ISSUE TITLE
Fix the rickroll!

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#42]
Somehow while merging things I think I broke the [ + ] button in the lower right-hand corner that makes the rickroll appear, so now we can't rickroll our visitors!

This is a good issue if you want to try to read the current javascript, learn how it works and implement a fix. Also good if you like playing pranks on our poor guests.

**Comment by arthurmatthew** [comment]
I am able to fix this issue, is that okay?

**Comment by arthurmatthew** [comment]
I'm going to work on this issue.
