### ISSUE TITLE
Improve organization of CSS

### ISSUE THREAD

**Issue by michaella23** [jeffreycharters/station#55]
Group CSS for different sections of the site, in the same order that they appear in the HTML document. Use code comments to make it easier to find styling for particular elements.

**Comment by michaella23** [comment]
I would be happy to work on this myself.

**Comment by ChaudharyRaman** [comment]
Hi @michaella23  , I would like to work on this. Can you assign it to me?

**Comment by michaella23** [comment]
@ChaudharyRaman, sure! Thanks for volunteering.
