### ISSUE TITLE
Update contributing.md file

### ISSUE THREAD

**Issue by Njong392** [jeffreycharters/station#56]
I know that the contributing.md file already does a great job listing this project's essence. I thought we could update it with steps on how to help new contributors do stuff like fork, clone, commit their changes, and push back to this repo. 

Should in case this issue is approved, I would like to be assigned to it.

**Comment by michaella23** [comment]
This is a great issue @Njong392! Would appreciate you working on this. Thanks!

**Comment by jeffreycharters** [comment]
Hey Emy! Could you put in there that the page will be constantly evolving and please don't get hurt if someone's contribution gets updated/modified/deleted at some point in the future? Maybe that if they really like some part they can publish their own fork somewhere?

**Comment by Njong392** [comment]
Definitely! This is an important note :+1:
