### ISSUE TITLE
Oh no! Fix the list bug

### ISSUE THREAD

**Issue by michaella23** [jeffreycharters/station#58]
Uh-oh. When pull requests were merged with the main, we ended up with two sets of the favourite lists. The second one looks a little wonky. Double check the HTML and CSS to resolve this conflict.

**Comment by Noothan-am** [comment]
hey @michaella23 will you assign me this?

**Comment by michaella23** [comment]
@Noothan-am, yes please give it a go!! Thank you.

**Comment by Noothan-am** [comment]
@michaella23 do I need to solve this part? 
![image](https://user-images.githubusercontent.com/100135382/193421272-3b5cb702-2465-4a33-ab00-04e0e3f24549.png)

**Comment by michaella23** [comment]
@Noothan-am Yes. I think that's part of it.  Someone had also written a media query so that the lists stack on top of each other on smaller screens. Will you see if this feature is still working too? Thanks!

**Comment by Noothan-am** [comment]
is this ok?
![image](https://user-images.githubusercontent.com/100135382/193422195-969222d9-0504-4dee-8260-064aaf97f677.png)
and responsive 
![image](https://user-images.githubusercontent.com/100135382/193422205-a333af24-a521-4bcc-a26d-58f0ef4919c7.png)
