### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#6]
Create a guide in the readme to help people who are new here figure out how to take their first steps. We'll assume very little knowledge of working in Git, as best we can.

**Comment by Njong392** [comment]
Just here to hop on this issue a bit. Maybe we can recreate the README to state the purpose of the project, what and how people should be contributing, and steps for devs who have never tried open source before.

**Comment by jeffreycharters** [comment]
Do you have any interest in making a first crack at it? I'm happy to otherwise. Just clone this repo, create a "readme-redo" or similar branch and we can work on changes there?

**Comment by jeffreycharters** [comment]
Unless you've started, I may actually jump on this one myself? I want to try to give people all the resources they might need to get started..

**Comment by Njong392** [comment]
Sure thing Jeffery! Go ahead and work on it. I was just making a comment about the README. I would love to see how you approach this and if I can help :)

**Comment by jeffreycharters** [comment]
I've made a few changes -- what do you think now? If it looks good I'll close this issue, and we can always create something similar if we come up with changes down the road.
