### ISSUE TITLE
Visitor counter bug

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#61]
I noticed while frantically refreshing the page that at some point the `Number of visits: #` counter increases by two every time the page loads. Can someone track down why this is happening and implement a fix?

Thanks!

**Comment by laxmanbalaraman** [comment]
I found the issue! someone has implemented the function for `number of visit` twice. That why we have this issue.
can u assign this to me. I can fix this. : )

**Comment by jeffreycharters** [comment]
I figured it might be something like that -- we're still learning how things work too, so I'm not totally surprised we let something like this happen. Thank you!

**Comment by laxmanbalaraman** [comment]
> I figured it might be something like that -- we're still learning how things work too, so I'm not totally surprised we let something like this happen. Thank you!

I am too a beginner trying to understand how this git and GitHub work. I have made a lot of mistakes today but definitely learned a lot from them.

Btw i have created a PR for this issue @jeffreycharters. Kindly review it. Thanks!
