### ISSUE TITLE
Add cricket to the list of favourite sports

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#62]
Since I am also new to this, I approved a pull request adding cricket to the list of favourite sports, but I don't see it there?

This should be a very easy fix, perfect for someone who is anxious about getting involved. Please let us know if you'd like to be assigned this issue.

**Comment by Santhusha-bit** [comment]
Can I work on this?

**Comment by jeffreycharters** [comment]
Yeah, go for it!

**Comment by Santhusha-bit** [comment]
Done
