### ISSUE TITLE
[DOCS]: add a license

### ISSUE THREAD

**Issue by akebu6** [jeffreycharters/station#65]
Hey, I looked at the project and it has no license which tells contributors and others who may want to use the project what levels of access they can have. I propose to give the project either an MIT license or an Apache one, and can I work on adding it?

N.B: licenses are good to show the level of open source-ness of a project

**Comment by michaella23** [comment]
@akebu6 I didn't know that about licenses. It would be great if you could add one. Thank you!

**Comment by akebu6** [comment]
Great, just assign it to me and I can have it done in a few hours

**Comment by akebu6** [comment]
created the PR that resolves the issue, kindly review it for any changes
