### ISSUE TITLE
Changing Text and border

### ISSUE THREAD

**Issue by DHCJS** [jeffreycharters/station#69]
Hi there, I am new to Open Source Contribution, so if you are willing, I want to do simple stuff such as changing how the text looks like.

- Upper case letter in every new word

![image](https://user-images.githubusercontent.com/80773310/193438325-2caf578e-e6fe-4795-af49-a07ff28d606a.png)

- Another upper case
![image](https://user-images.githubusercontent.com/80773310/193438345-210b68d1-7413-448b-9fd7-35b5fd352655.png)

- Another one
 
![image](https://user-images.githubusercontent.com/80773310/193438361-1bb421cf-797e-4e24-9502-97262f751b3e.png)

- and the last one
![image](https://user-images.githubusercontent.com/80773310/193438375-8066c27e-bf88-4dec-a34e-951242ff2ed2.png)

I'd like to make the border into soft edges rather than sharp edges.

That's all. If it suits you, please assign this issue to me.

Thank you!

**Comment by michaella23** [comment]
Go for it @DHCJS !

**Comment by DHCJS** [comment]
Thank you, @michaella23. I've done it; please kindly check it when you are available. 
I am also trying code review, which is new to me; if it bothers the comment section, please let me know. Thank you!
