### ISSUE TITLE
Left justify most of the content

### ISSUE THREAD

**Issue by jeffreycharters** [jeffreycharters/station#77]
I think it would make things look better if the content below the hero image were to be left-justified instead of centered. Anyone else feel this? It should all be within a container div, so left-justifying should still look nice.

Have a try, see what you can do! Let us know if you want to tackle this so you can be assigned.

**Comment by ramdhanihendrie** [comment]
I am interested in this issue. please assign it to me

**Comment by jeffreycharters** [comment]
All yours, good luck!
