### ISSUE TITLE
[feat]: Make the testimonials section a slider

### ISSUE THREAD

**Issue by publikphigor** [jeffreycharters/station#89]
The current testimonials section is cool but it'd be nice to make it into a slider that auto-updates according to the number of slides.

Each slide will represent a testimonial.
Contributors can then add their own testimonial in the codebase.

**Comment by michaella23** [comment]
That sounds like a great feature! I've assigned this issue to you, and you can get started when you're ready.

**Comment by publikphigor** [comment]
Awesome! Can't wait to push codes 🚀🚀
