### ISSUE TITLE
[SUGGESTION]: Add Open Source blog post to repo

### ISSUE THREAD

**Issue by slim-codes** [jeffreycharters/station#90]
**I just published my first [blog post](https://dev.to/slimcodes/what-is-open-source-and-why-should-you-care-47l0) on Dev.to 2 days ago. The post is an article on getting started with Open Source. It's my first post as a technical writer, so it's not perfect but it's a start. Coincidentally, I stumbled upon this repo today and I just realized that it'd be nice to be able to include the post here to help others who might be new to the Open Source space.**

**Comment by michaella23** [comment]
Hey Slim! Thanks for submitting this issue. I think this would be a great addition to the page! You can start on it whenever you're ready.
